[package]
name = "Raycasting"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.26.0"
image = "0.25.2"
once_cell = "1.19.0"
rodio = "0.19.0"
gilrs = "0.10.3"
gif = "0.13.1"
